name: Publish Atmoos.Sphere.BenchmarkDotNet

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Sphere.BenchmarkDotNet.csproj'

jobs:
  publish-sphere-benchmarkdotnet:

    permissions:
      contents: write

    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.Sphere.BenchmarkDotNet/Atmoos.Sphere.BenchmarkDotNet.csproj'
      tag-prefix: 'sphere.benchmarkdotnet'
    secrets: inherit
