name: Publish Atmoos.Sphere

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Sphere.csproj'

jobs:
  publish-sphere:
    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.Sphere/Atmoos.Sphere.csproj'
      tag-prefix: 'sphere'
    secrets: inherit
