name: Publish Atmoos.Sphere

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Sphere.csproj'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  Prefix: 'sphere'
  Project: 'source/Atmoos.Sphere/Atmoos.Sphere.csproj'
  DotNetVersion: 8.0.x
  NugetKey: ${{ secrets.CREATENEWNUGETPACKAGE }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DotNetVersion }}
      - uses: tedd/publish-nuget-neo@v1
        with:
          NUGET_KEY: ${{env.NugetKey}}
          PROJECT_FILE_PATH: ${{env.Project}}
          TAG_COMMIT: true
          TAG_FORMAT: ${{env.Prefix}}/v*
